website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, make_response, current_app
from flask_login import login_required, current_user
from .models import List, Task, Plant
from . import db
import json
from datetime import datetime, timedelta, date
from collections import defaultdict
import calendar as calendar_lib
import locale



views = Blueprint('views', __name__)

@views.route('/', methods=['GET'])
def main():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    else:
        return render_template('main.html', user=current_user)

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        list_title = request.form.get('list_title', '').strip()

        if not list_title:
            flash('Nazwa listy musi mieć przynajmniej 1 znak!', category='error')
        else: 
            new_list = List(user_id=current_user.id, list_title=list_title)
            db.session.add(new_list)
            db.session.commit()
            flash('Lista została dodana!', category='success')
            return redirect(url_for('views.go_to_list', list_id = new_list.id))
        
    user_lists = List.query.filter_by(user_id=current_user.id).all()
    return render_template('home.html', user=current_user, lists=user_lists)

@views.route('/redirect-to-list')
@login_required
def go_to_list():
    list_id = request.args.get('list_id')
    if not list_id:
        return redirect(url_for('views.home'))
    return redirect(url_for('views.show_list', list_id=list_id))
    

@views.route('/<int:list_id>', methods=['GET', 'POST'])
@login_required
def show_list(list_id):
    current_list = List.query.filter_by(id=list_id, user_id=current_user.id).first()

    if not current_list:
        flash('Nie znaleziono listy.', category='error')
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        action = request.form.get("action")

        if action == 'add_task':
            task_data = request.form.get('task', '').strip()
            reminder = request.form.get('reminder')

            if not task_data:
                flash('Zadanie musi mieć przynajmniej 1 znak!', category='error')
            else:
                if reminder:
                    if request.form.get('deadline_date') and request.form.get('deadline_time'):
                        deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                        deadline_time = datetime.strptime(request.form.get('deadline_time'), '%H:%M').time()
                        new_task = Task(data=task_data, list_id=list_id, user_id=current_user.id, deadline_date = deadline_date, deadline_time = deadline_time, reminder = True)
                    else:
                        flash('Wybierz datę i godzinę, aby móc otrzymać przypomnienie!', category='error')
                        return redirect(url_for('views.show_list', list_id=list_id), code=303)   
                else:
                    if request.form.get('deadline_date') and request.form.get('deadline_time'):
                        deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                        deadline_time = datetime.strptime(request.form.get('deadline_time'), '%H:%M').time()
                        new_task = Task(data=task_data, list_id=list_id, user_id=current_user.id, deadline_date = deadline_date, deadline_time = deadline_time)
                    elif request.form.get('deadline_date') and not request.form.get('deadline_time'):
                        deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                        new_task = Task(data=task_data, list_id=list_id, user_id=current_user.id, deadline_date = deadline_date)
                    elif request.form.get('deadline_time') and not request.form.get('deadline_date'):
                        flash('Wybierz datę, aby móc ustawić godzinę!', category='error')
                        return redirect(url_for('views.show_list', list_id=list_id), code=303) 
                    else:
                        new_task = Task(data=task_data, list_id=list_id, user_id=current_user.id)

            db.session.add(new_task)
            db.session.commit()
            flash('Dodano zadanie!', category='success')

            return redirect(url_for('views.show_list', list_id=list_id), code=303) 
        elif action == 'edit_task':
            task_id = request.form.get('task_id')
            task_data = request.form.get('task', '').strip()
            reminder = request.form.get('reminder')

            task = Task.query.filter_by(id=task_id, user_id=current_user.id).first()

            if not task:
                flash('Nie znaleziono zadania.', category='error')
                return redirect(url_for('views.show_list', list_id=list_id), code=303) 

            if task_data:
                task.data = task_data
            else: 
                task.data = task.data

            if reminder:
                if request.form.get('deadline_date') and request.form.get('deadline_time'):
                    task.deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                    task.deadline_time = datetime.strptime(request.form.get('deadline_time'), '%H:%M').time()
                    task.reminder = True
                    task.reminder_sent = False 
                else:
                    flash('Wybierz datę i godzinę, aby móc otrzymać przypomnienie!', category='error')
                    return redirect(url_for('views.show_list', list_id=list_id), code=303)    
            else:
                if request.form.get('deadline_date') and request.form.get('deadline_time'):
                    task.deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                    task.deadline_time = datetime.strptime(request.form.get('deadline_time'), '%H:%M').time()
                elif request.form.get('deadline_time') and not request.form.get('deadline_date'):
                    flash('Wybierz datę, aby móc ustawić godzinę!', category='error')
                    return redirect(url_for('views.show_list', list_id=list_id), code=303) 
                elif request.form.get('deadline_date') and not request.form.get('deadline_time'):
                    task.deadline_date = datetime.strptime(request.form.get('deadline_date'), '%Y-%m-%d').date()
                else:
                    task.deadline_date = None
                    task.deadline_time = None
                task.reminder = False
                task.reminder_sent = False 

            db.session.commit()
            flash('Zadanie zaktualizowane!', category='success')

            return redirect(url_for('views.show_list', list_id=list_id), code=303)

    return render_template('list.html', list=current_list, user=current_user)


@views.route('/delete-list', methods=['POST'])
@login_required
def delete_list():
    list = json.loads(request.data)
    listId = list['listId']
    list = List.query.get(listId)
    if list:
        if list.user_id == current_user.id:
            db.session.delete(list)
            db.session.commit()
    
    return jsonify({})

@views.route('/update_task/<int:task_id>', methods=['POST'])
@login_required
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    user = current_user

    task.if_done = 'if_done' in request.form

    if task.if_done:
        task.completed_at = datetime.now()
        if not task.first_check:
            task.first_check = True
            user.water_points += 1
            user.daily_checked_tasks += 1
    else:
        task.completed_at = None

    db.session.commit()
    return redirect(url_for('views.show_list', list_id=task.list_id))


@views.route('/update_task_calendar/<int:task_id>', methods=['POST'])
@login_required
def update_task_calendar(task_id):
    task = Task.query.get_or_404(task_id)
    user = current_user

    task.if_done = 'if_done' in request.form

    if task.if_done:
        task.completed_at = datetime.now()
        if not task.first_check:
            task.first_check = True
            user.water_points += 1
            user.daily_checked_tasks += 1
    else:
        task.completed_at = None

    db.session.commit()
    return redirect(url_for('views.calendar'), code=303)

@views.route('/delete-task', methods=['POST'])
@login_required
def delete_task():
    task = json.loads(request.data)
    taskId = task['taskId']
    task = Task.query.get(taskId)
    if task:
        if task.user_id == current_user.id:
            db.session.delete(task)
            db.session.commit()
    
    return jsonify({})

@views.route("/calendar", methods=['POST', 'GET'])
@login_required
def calendar():
    user = current_user
    today = datetime.now().date()
    start_date = today - timedelta(days=365)
    end_date = today + timedelta(days=365)
    
    tasks = Task.query.filter(
        Task.deadline_date.isnot(None),
        Task.user_id == user.id
    ).all()

    events = [
        {
            "title": task.data,
            "start": task.deadline_date.strftime("%Y-%m-%d"),
            "allDay": True
        }
        for task in tasks
        if today <= task.deadline_date <= end_date
    ]

    tasks_by_date = defaultdict(list)
    for task in tasks:
        if task.deadline_date:
            ds = task.deadline_date.strftime("%Y-%m-%d")
            if start_date <= task.deadline_date <= end_date:
                tasks_by_date[ds].append(task)

    tasks_by_date = dict(tasks_by_date)

    all_days = [
        start_date + timedelta(days=i)
        for i in range((end_date - start_date).days + 1)
    ]

    dni = ['poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota', 'niedziela']
    miesiące = ['stycznia', 'lutego', 'marca', 'kwietnia', 'maja', 'czerwca',

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='home.css') }}" rel="stylesheet" />
{% endblock %}

{% block content%}
<h2 class="title">Listy zadań</h2>

<div class="list-container">
<ul class="list" id="lists">
  {% for list in lists %}
  <li class="item">
    <a id="list" href="{{ url_for('views.show_list', list_id=list.id) }}" class="list-title">{{ list.list_title }}</a>
    {% if not list.is_default %}
      <button type="button" class="close" onClick="deleteList({{ list.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
    {% endif %}
  </li>
  {% endfor %}
</ul>

<form method="POST">
  <label for="list_title"></label>
  <input type="text" name="list_title" id="list_title" class="list-title-input" value="" autocomplete="off" placeholder="Wpisz tytuł listy..." required>
  <br />
  <div>
    <button type="submit" class="btn btn-secondary btn-sm">Dodaj listę</button>
  </div>
</form>
</div>

<!-- JAVA SCRIPT-->
<script>
  // usuwanie listy
  function deleteList(listId) {
  fetch("/delete-list", {
    method: "POST",
    body: JSON.stringify({ listId: listId }),
  }).then((_res) => {
    window.location.href = "/home";
  });
}
</script>
{% endblock %}

website/templates/list.html
{% extends "base.html" %}
{% block title %}{{list.list_title}}{% endblock %}
{% block head %}
<link href="{{ url_for('static', filename='list.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
<h2 class="list-title"> {{list.list_title}} </h2>

<div class="task-list">
<!-- zadania niewykonane -->
<ul class="tasks" id="tasks">
  {% for task in list.tasks if not task.if_done%}
  <li class="task">
    <!-- info o zadaniu -->
    <div class="task-header">
      <form method="POST" action="{{ url_for('views.update_task', task_id=task.id) }}" class="form-check">
        <input type="checkbox" name="if_done" value="true" {% if task.if_done %}checked{% endif %} onchange="this.form.submit()">
      </form>
      <p class="task-data">{{ task.data }}</p>
      <span class="task-deadline text-muted">
        <i class="fa-solid fa-calendar-days"></i> {{ task.deadline_date.strftime('%d.%m.%Y') if task.deadline_date else '-' }}
        <i class="fa-solid fa-clock"></i> {{ task.deadline_time.strftime('%H:%M') if task.deadline_time else '-' }}
        {% if task.reminder %} <i class="fa-solid fa-bell"></i> {% endif %}
      </span>
      <button type="button" class="edit text-muted" data-date="{{ iso }}" onClick="editTaskForm(this)">
        <i class="fa-solid fa-pen-to-square"></i>
      </button>
      <button type="button" class="close text-muted" onClick="deleteTask({{ task.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <!-- formularz edytowania zadania -->
    <div class="edit-task-form" style="display: none;">
      <form method="POST">
        <input type="hidden" name="action" value="edit_task">
        <input type="hidden" name="task_id" value="{{ task.id }}">
        <input type="text" name="task" id="task" class="task-data-input" autocomplete="off" placeholder="Wpisz treść zadania..."><br />
        <span class="text-muted">
          <i class="fa-solid fa-calendar-days"></i>
          <input type="date" name="deadline_date" id="deadline_date" class="deadline-date">
        </span>
        <span class="text-muted">
          <i class="fa-solid fa-clock"></i>
          <input type="time" name="deadline_time" id="deadline_time" class="deadline-time">
        </span>
        <label for="reminder" class="text-muted"><i class="fa-solid fa-bell"></i></label>
        <input type="checkbox" name="reminder" id="reminder">
        <div class="submit-add-task-form-buttons">
          <button type="button" class="btn btn-outline-secondary btn-sm" onclick="cancelEditTaskForm(this)">Anuluj</button>
          <button type="submit" class="btn btn-primary btn-sm">Edytuj zadanie</button>
        </div>
      </form>
    </div>
  </li>
  {% endfor %}
</ul>

<!-- przycisk "dodaj zadanie" i "pokaż wykonane zadania" -->
<button type="button" class="toggle-add-task-form btn btn-secondary btn-sm" onclick="addTaskForm(this)">Dodaj zadanie</button>
{% set done_tasks = list.tasks | selectattr('if_done') | list %}
{% if done_tasks %}
  <button type="button" id="show-done-tasks" class="btn btn-outline-secondary btn-sm" onclick="showDoneTasks(this)">Pokaż wykonane zadania</button>
{% endif %}

<!-- formularz dodawania zadania -->
<div class="add-task-form" id="add-task-form" style="display: none;">
    <form method="POST">
      <input type="hidden" name="action" value="add_task">
      <input type="text" name="task" id="task" class="task-data-input" autocomplete="off" placeholder="Wpisz treść zadania..." required><br>
      <span class="text-muted">
        <i class="fa-solid fa-calendar-days"></i>
        <input type="date" name="deadline_date" id="deadline_date" class="deadline-date">
      </span>
      <span class="text-muted">
        <i class="fa-solid fa-clock"></i>
        <input type="time" name="deadline_time" id="deadline_time" class="deadline-time">
      </span>
      <label for="reminder" class="text-muted"><i class="fa-solid fa-bell"></i></label>
      <input type="checkbox" name="reminder" id="reminder">
      <div class="submit-add-task-form-buttons">
        <button type="button" class="btn btn-outline-secondary btn-sm" onclick="cancelTaskForm(this)">Anuluj</button>
        <button type="submit" class="btn btn-primary btn-sm">Dodaj zadanie</button>
      </div>
    </form>
</div>
</div>

<!-- wykonane zadania -->
<div id="done-tasks" style="display: none;">
<div class="task-list">
{% set done_tasks = list.tasks | selectattr('if_done') | list %}
{% if done_tasks %}
<ul class="tasks" id="tasks">
  <h5>Wykonane</h5>
  {% for task in list.tasks if task.if_done %}
  <li class="task">
    <!-- info o zadaniu -->
    <div class="task-header">
      <form method="POST" action="{{ url_for('views.update_task', task_id=task.id) }}" class="form-check">
      <input type="checkbox" name="if_done" value="true" {% if task.if_done %}checked{% endif %} onchange="this.form.submit()">
      </form>
      <p class="task-data">{{ task.data }}</p>
      <span class="task-deadline text-muted">
      <i class="fa-solid fa-calendar-days"></i> {{ task.deadline_date.strftime('%d.%m.%Y') if task.deadline_date else '-' }}
      <i class="fa-solid fa-clock"></i> {{ task.deadline_time.strftime('%H:%M') if task.deadline_time else '-' }}
      {% if task.reminder %} <i class="fa-solid fa-bell"></i> {% endif %}
      </span>
      <button type="button" class="edit text-muted" data-date="{{ iso }}" onClick="editTaskForm(this)">
        <i class="fa-solid fa-pen-to-square"></i>
      </button>
      <button type="button" class="close text-muted" onClick="deleteTask({{ task.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <!-- formularz edytowania zadania -->
    <div class="edit-task-form" style="display: none;">
      <form method="POST">
        <input type="hidden" name="action" value="edit_task">
        <input type="hidden" name="task_id" value="{{ task.id }}">
        <input type="text" name="task" id="task" class="task-data-input" autocomplete="off" placeholder="Wpisz treść zadania..."><br />
        <span class="text-muted">
          <i class="fa-solid fa-calendar-days"></i>
          <input type="date" name="deadline_date" id="deadline_date" class="deadline-date">
        </span>
        <span class="text-muted">
          <i class="fa-solid fa-clock"></i>
          <input type="time" name="deadline_time" id="deadline_time" class="deadline-time">
        </span>
        <label for="reminder" class="text-muted"><i class="fa-solid fa-bell"></i></label>
        <input type="checkbox" name="reminder" id="reminder">
        <div class="submit-add-task-form-buttons">
          <button type="button" class="btn btn-outline-secondary btn-sm" onclick="cancelEditTaskForm(this)">Anuluj</button>
          <button type="submit" class="btn btn-primary btn-sm">Edytuj zadanie</button>
        </div>
      </form>
    </div>
  </li>
  {% endfor %}
</ul>
{% endif %}
</div>
</div>

<!-- JAVA SCRIPT -->
<script>
window.addEventListener("load", () => {
  if (window.history.replaceState) {
    window.history.replaceState(null, "", window.location.pathname);
  }
});

// formularz dodawania zadania
const addTaskForm = (button) => {
  const formContainer = document.getElementById('add-task-form'); 
  
  formContainer.style.display = 'block';        
  button.style.display = 'none';                 
  document.querySelectorAll('.edit-task-form').forEach(fc => fc.style.display = 'none');
  document.querySelectorAll('.edit').forEach(btn => btn.style.display = 'inline-block');

  // scroll do formularza na środek
  formContainer.scrollIntoView({ behavior: 'smooth', block: 'center' });
};

// anulowanie dodawania zadania
const cancelTaskForm = (button) => {
  const form = button.closest('form');
  const formContainer = form.parentElement;
  
  form.reset();
  formContainer.style.display = 'none';          

  // pokaż przycisk "Dodaj zadanie"
  const addTaskButton = document.querySelector('.toggle-add-task-form');
  if (addTaskButton) {
    addTaskButton.style.display = 'inline-block';
  }
};

// formularz edytowania zadania
const editTaskForm = (button) => {
  const currentTask = button.closest('.task'); 
  const formContainer = currentTask.querySelector('.edit-task-form');
  const form = formContainer.querySelector('form');

  // ukryj wszystkie formularze i pokaż ich przyciski 
  document.querySelectorAll('.edit-task-form').forEach(fc => fc.style.display = 'none');
  document.querySelectorAll('.edit').forEach(btn => btn.style.display = 'inline-block');
  document.querySelectorAll('.add-task-form').forEach(fc => fc.style.display = 'none');
  document.querySelectorAll('.toggle-add-task-form').forEach(btn => btn.style.display = 'inline-block');

  // pokaż tylko formularz w bieżącym dniu
  formContainer.style.display = 'block';
  button.style.display = 'none';

  // scroll do formularza
  formContainer.scrollIntoView({ behavior: 'smooth', block: 'center' });
};

// anulowanie edytowania zadania
const cancelEditTaskForm = (button) => {
  const form = button.closest('form');
  const formContainer = form.parentElement;
  const currentTask = formContainer.closest('.task');
  const toggleButton = currentTask.querySelector('.edit');

  form.reset();
  formContainer.style.display = 'none';
  toggleButton.style.display = 'inline-block';
};

// pokaż/ukryj wykonane zadania
const showDoneTasks = (button) => {
  const doneTasks = document.getElementById('done-tasks');

  if (doneTasks.style.display === 'none' || doneTasks.style.display === '') {
    doneTasks.style.display = 'block';
    button.textContent = 'Ukryj wykonane zadania';
  } else {
    doneTasks.style.display = 'none';
    button.textContent = 'Pokaż wykonane zadania';
  }
};
</script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Logowanie{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='login.css') }}" rel="stylesheet" />
{% endblock %}

{% block nav %}{% endblock %}

{% block content %}

<form method="POST">
    <h3>Logowanie</h3>
    <div class="form-group">
        <label for="email">E-mail:</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Wpisz swój e-mail...">
    </div>
    <div class="form-group">
        <label for="password">Hasło:</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Wpisz swoje hasło...">
    </div>
    <button type="submit" class="btn btn-primary login">Zaloguj się</button>

    <p>Nie masz jeszcze konta?</p>
    <a class="nav-item nav-link" id="signUp" href="/sign-up">
    <button type="button" class="btn btn-outline-secondary btn-sm signup">Zarejestruj się</button>
    </a>
    
</form>

{% endblock %}

website/templates/main.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" />
{% endblock %}

{% block title %}Grow List{% endblock %}

{% block nav %}{% endblock %}
{% block content %}

    <img src="{{ url_for('static', filename='images/logo.png') }}" class="logo" alt="logo">
    <h4>Nie masz jeszcze konta?</h4>
    <button type="button" class="btn btn-outline-secondary"><a class="link" id="signUp" href="/sign-up">Zarejestruj się</a></button>
    
    <h4>Masz już konto?</h4>
    <button type="button" class="btn btn-primary"><a class="link" id="login" href="/login">Zaloguj się</a></button>
    
{% endblock %}

{% block plant %}{% endblock %}

website/templates/plant_shelf.html
{% extends "base.html" %}
{% block title %}Półka{% endblock %}
{% block head %}
<link href="{{ url_for('static', filename='plant_shelf.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
<h2 class="title"> Moja półka </h2>


<ul class="plants" id="plants">
  {% for plant in plants %}
  <li class="plant">
    {% if plant.final_wither_stage == 3 %}
      {% if plant.final_growth == 1 %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_1_dead.png') }}" class="plant-img plant-img--1" alt="Uschnięta roślinka"></div>
      {% elif plant.final_growth == 2 %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_2_dead.png') }}" class="plant-img plant-img--2" alt="Uschnięta roślinka"></div>
      {% else %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_3_dead.png') }}" class="plant-img plant-img--3" alt="Uschnięta roślinka"></div>
      {% endif %}
    {% else %}
      {% if plant.final_growth == 1 %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_1.png') }}" class="plant-img plant-img--1" alt="1. faza rozwoju"></div>
      {% elif plant.final_growth == 2 %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_2.png') }}" class="plant-img plant-img--2" alt="2. faza rozwoju"></div>
      {% elif plant.final_growth == 3 %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_3.png') }}" class="plant-img plant-img--3" alt="3. faza rozwoju"></div>
      {% else %}
        <div class="plant-img-container"><img src="{{ url_for('static', filename='images/plant_4.png') }}" class="plant-img plant-img--4" alt="4. faza rozwoju"></div>
      {% endif %}
    {% endif %}
    
    <p class="date">Początek wzrostu: <br>{{ plant.created_at.strftime('%d-%m-%Y %H:%M') }}</p>
    <p class="date">Koniec wzrostu: <br>{{ plant.finished_at.strftime('%d-%m-%Y %H:%M') }}</p>
  </li>
  {% endfor %}
</ul>
  

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Rejestracja{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='sign_up.css') }}" rel="stylesheet" />
{% endblock %}

{% block nav %}{% endblock %}

{% block content%}
<form method="POST">
    <h3>Rejestracja</h3>
    <div class="form-group">
        <label for="email">E-mail:</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Wpisz swój e-mail..." required>
    </div>
    <div class="form-group">
        <label for="firstName">Nazwa użytkownika:</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Wpisz swoją nazwę użytkownika..." required>
    </div>
    <div class="form-group">
        <label for="password1">Hasło:</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Wpisz swoje hasło..." required>
    </div>
    <div class="form-group">
        <label for="password2">Potwierdź hasło:</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Potwierdź swoje hasło..." required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary signup">Zarejestruj się</button>

    <p>Masz już konto?</p>
    <a class="nav-item nav-link" id="login" href="/login">
    <button type="button" class="btn btn-outline-secondary btn-sm login">Zaloguj się</button>
    </a>
    
</form>
{% endblock %}